* Devil Mode

[[https://melpa.org/#/devil][file:https://melpa.org/packages/devil-badge.svg]]
[[https://stable.melpa.org/#/devil][file:https://stable.melpa.org/packages/devil-badge.svg]]
[[https://mastodon.social/@susam][file:https://img.shields.io/badge/mastodon-%40susam-%2355f.svg]]

Devil mode trades your comma key in exchange for a modifier-free
editing experience in Emacs!  Yes, the comma key!  The key you would
normally wield for punctuation in nearly every corner of text.  Yes,
this is twisted!  It would not be called the Devil otherwise, would
it?  If it were any more rational, we might call it something divine,
like, uh, the God mode?  But alas, there is nothing divine to be found
here.  Welcome, instead, to the realm of the Devil!  You will be
granted the occasional use of the comma key for punctuation, but only
if you can charm the Devil!  But beware, for in this sinister domain,
you must relinquish your comma key and embrace an editing experience
that whispers wicked secrets into your fingertips!

Read the [[./MANUAL.org][manual]] for more details on how to use Devil.

** Channels
:PROPERTIES:
:CUSTOM_ID: channels
:END:
The author of this project hangs out at the following places online:

- Website: [[https://susam.net][susam.net]]
- Mastodon: [[https://mastodon.social/@susam][@susam@mastodon.social]]
- Twitter: [[https://twitter.com/susam][@susam]]
- GitHub: [[https://github.com/susam][@susam]]

You are welcome to subscribe to, follow, or join one or more of the
above channels to receive updates from the author or ask questions
about this project.

* Support
:PROPERTIES:
:CUSTOM_ID: support
:END:
To report bugs, suggest improvements, or ask questions, [[https://github.com/susam/devil/issues][create issues]].

** More
:PROPERTIES:
:CUSTOM_ID: more
:END:
See [[https://github.com/susam/emacs4cl][Emacs4CL]], a DIY quick-starter kit to set up Emacs for Common Lisp
programming.

See [[https://github.com/susam/emfy][Emfy]], a DIY quick-starter kit to set up Emacs for general purpose
editing and programming.
